name = "PADI"
uuid = "d7b96371-e7cf-4969-a096-f980e5147251"
authors = ["Laurence <ldenneulin@montesquiou.info>", "Vincent <vincent.tardieux@epita.fr>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
CompilerSupportLibraries_jll = "e66e0078-7015-5450-92f7-15fbd957f2ae"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
EasyFITS = "a977f4a2-36a7-4172-89e7-19c2726f82e5"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FITSIO = "525bcba6-941b-5504-bd06-fd0dc1a4d2eb"
ImageQualityIndexes = "2996bd0c-7a13-11e9-2da2-2f5ce47296a9"
InterpolationKernels = "16730964-a2ec-11e9-36fa-47a4f82bfac6"
LazyAlgebra = "aeaa251e-9d76-11e9-311b-83636bf44738"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearInterpolators = "2fc109c4-9d77-11e9-32ff-e5c650334c16"
OptimPackNextGen = "080ffe24-4a27-4ab0-ad71-7b624e73ef8d"
PRIMA = "0a7d04aa-8ac2-47b3-b7a7-9dbd6ad661ed"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TwoDimensional = "1907e7ba-7586-4310-a2ba-dd01462aeb50"

[compat]
CSV = "0.10.15"
DataFrames = "1.7.0"
DelimitedFiles = "1.9.1"
EasyFITS = "0.6.1"
ImageQualityIndexes = "0.3.7"